### PR TITLE
small typo

### PR DESCRIPTION
**Pull request by atsju**

### CODE REVIEW

**Comment by gr5** [comment]
I approve this.  I'll ask dave to do this merge after #8 is merged.

**Comment by atsju** [comment]
> I approve this. I'll ask dave to do this merge after #8 is merged.

You "must" Request your review on the right and then approve in review mode. There you can leave a message but it's the actual "approved" Flag for github

**Comment by gr5** [comment]
Maybe I used the wrong word.  I "agree" that this pull request makes sense.  Is that more clear?  This pull request is now on my personal radar.  I consider it a high priority (because it is easy - not because it is critical).  I will bug Dale to approve this one after #8.

Thanks for pointing out the "reviewers" request on the right.

After #8 is approved I'll be commenting on the other linux PRs as well.

**Comment by gr5** [comment]
I do want to chat with you on phone or discord by the way.  Email me at gr _at_ gr5.org please to pick a time.  Let's talk about git processes.

**Review by gr5 — COMMENTED** [review]
Looks great.  I actually saw this popup for I think the first time yesterday when testing out DFTF on ubuntu.

**Review by githubdoe — APPROVED** [review]

**Pull request merged**
