### PR TITLE
Fix all ui files warnings

### PR DESCRIPTION
**Pull request by atsju**
Some have simply been edited with qtdesigner.
Some needed manual edition, and I believe they would be same if they had been fully recreated with a recent QTdesigner.

### CODE REVIEW

**Review by githubdoe — CHANGES_REQUESTED** [review]
It is useless to modify .ui files.  They will change the next time Qt is compiled using the Qt  build which is what I do.

**Comment by atsju** [comment]
Could you explain me what is this QT build ? 
because if they change it means they are not input files and something is on your computer but not on github.
Or are they opened, modified, and saved by QT build for obscure reasons ?

**Review by githubdoe — COMMENTED** [review]
It is useless to modify .ui files.  They will change the next time Qt is compiled using the Qt  build which is what I do.

**Comment by githubdoe** [comment]
Damn I hate .Arg().   It is so hard to figure out what is being printed. After one has used PRINTF syntax  I can see in one glance what is being printed.  With .arg() you have to look in two places and then remember what the syntax is for arg and what each parameter may be specifying.  Aaaaaaaaggggg.

**Review by githubdoe — APPROVED** [review]
I will approve but just know the any and probably all .ui files will change the first time I compile.  I don't think you want to keep trying to change them.

**Review by githubdoe — COMMENTED** [review]
It is useless to modify .ui files.  They will change the next time Qt is compiled using the Qt  build which is what I do.

**Comment by githubdoe** [comment]
I just realized that perhaps you did not edit the .ui files that they are changing just because of re compliling.

**Comment by atsju** [comment]
> I will approve but just know the any and probably all .ui files will change the first time I compile. I don't think you want to keep trying to change them.
Please explain why .ui would be modified by compilation? this makes NO sense for me.
More probable is you open them with an IDE that modified them without telling you. But not the compilation process. Yes the simple fact opening .ui with QTdesigner and saving did some unexpected modifications but it's not the compilation process.

> I just realized that perhaps you did not edit the .ui files that they are changing just because of re compliling.
No I did it on purpose and manually directly in file and/or with QTdesigner

**Comment by githubdoe** [comment]
Qt creates the .ui files from data provided by QtCreator which is derived from the GUI that lets us create Qt forms (windows, dialogs and such).

Build is Qt lingo for make the files necessary to compile the program.
 It will create .cpp and .h files from those .ui files.  Those cpp files with "ui" in the name.

If one modifies the from like adding a button or deleting something or moving something it will recreate the .ui file.  
The next time you compile it will then make or remake the  .cpp and .h files related to that .ui file.

If I do a clean build it will delete all .cpp and .h files derived from those .ui files as well.  I will always do a clean build just before creating a final release.  Sometime due to a bug in Qt creator one needs to delete those related .cpp and .h files to get them updated.  So in the Qt IDE you can say clean.  It will delete all those files so that they can then be remade during the nest "Build"

**Comment by githubdoe** [comment]
Yes the .ui files will stay until one uses the GUI editor and not when they are compiled.    However Qt designer owns them and I think they should not be modified by the developer.

**Comment by atsju** [comment]
Thank you Dale I think it's clearer for me now.

I don't think QTdesigner owns the file. 
The .ui is just the way QTdesigner stored the thing you just draw.
image

From my understanding when you modify a windows, the QTdesigner opens the .ui you can modify the visual and it stores the .ui back. If QTdesigner "owned" the thing then you would have it stored somewhere in the project and it's note the case.

I agree .ui shall not be manually modified but only using QTdesigner or creator. Here I did only small modifications that do not break the compatibility with corresponding .cpp and .h.

If you "clean build" a .ui from now because you need to add a button or something, I hope that the warning will not come back. Because the IDE does not create the .ui from nothing or owning, it just modifies existing file. At least that's my understanding right now. I might be wrong.

**Review by githubdoe — COMMENTED** [review]
Sorry I still am not use to Git hub code reviews.  When I do diffs in Qt using git tools I ignore changes to .ui or at least remember changing the gui and thus the .ui changed.

Here seeing them on Github the triggered a false worry that you were changing them manually and not through the Qt IDE.

**Comment by atsju** [comment]
Please do not merge without testing. I did not have time to test the build yet

**Comment by gr5** [comment]
Dale I think you confused *.ui files with ui_*.h files.  The .h files are created based on the .ui files.  We don't check in the ui_*.h files as they are created as part of the build process.

The *.ui files however can be edited by opening them in qt creator and changing things from that editor which is what Julien did I think.  For example you had several layout widgets with the same name and I guess that somehow created compiler warnings.  In QT Creator you can change the name over on the properties window (like you can change many other things).

Even if he edited the ui files directly, they should hopefully still open in qt creator.  I'll test that today.

**Comment by githubdoe** [comment]
There are things you can do that corrupt Qt's ability to find or create slots based on the objects name.  I don't know exactly how it happens but it did to me even without my editing the .ui file.  I have a couple of .ui's that are now useless if I ever want to add objects who could send signals.  Very frustrating.  Sometimes I even recreated the whole form over again.  That makes me worry about manually modifying the .ui file.  Especially changing names of objects.  But who knows.

**Comment by gr5** [comment]
Okay so I can imagine if you change the name, now the name of the slot or signal could change.  So I hear your concern.

But I think he only edited the names of layouts which won't have any signals used.  I'm going to look at this some more.  I've already opened the first ui file in qt creator - in the gui editor.  So far it seems fine.

He also moved some things around...

**Comment by atsju** [comment]
I made some tests on the app and it seems to work fine.

Also I thank you for the explantations Dale. I better understand your concerns now. I think what you describe is not supposed to happen but this must be frustrating when it does. And from your experience : it does. 
I think that part of your experience is why clazy [level0 checks](https://github.com/KDE/clazy/blob/master/docs/checks/README-connect-by-name.md) recommends to not use [connect-by-name](https://github.com/KDE/clazy/blob/master/docs/checks/README-connect-by-name.md)

> He also moved some things around...

Only the 4 `horizontalSpacer_4` have been reordered (but I can put them back in original order). Remember to use the "hide whitespaces" option during github review. Changes have been surgical.

**Comment by githubdoe** [comment]
Sorry but I don't understand the issue with connect by name.  I'm use to it and expect it and don't know how to do otherwise.  When I click on those links it does not say much of anything except that people don't like it.  Clicking on the recommend link to learn more there is no more info other than to tell you that Qt uses connect by name.  Hmmm.

So there are hundreds of names with on_...   I like them because then I know what to look for and know that the routine is providing a service for a gui object.  Yes I know that changing the name of the GUI object will beak the connection and know where and how to fix and recover the intended connection.

Concerning connects:
  Qt introduced a newer connect macro system but I can never remember it's syntax and when I try to use it or look it up I get confused.  So I did not use it often.  I understand why the older system is not as good since it only error checks at run time.  But I can never remember how to do the other connect.  Not against using it however.  

Well I can never remember the old connect system either in truth.  I just go find old code I wrote to remind me if and when I need to do a connect.  Since there is little old code that uses the new system it is hit or miss of me finding an example.  Mostly miss.

**Comment by atsju** [comment]
> Sorry but I don't understand the issue with connect by name. I'm use to it and expect it and don't know how to do otherwise. When I click on those links it does not say much of anything except that people don't like it. Clicking on the recommend link to learn more there is no more info other than to tell you that Qt uses connect by name. Hmmm.

Same for me. I don't plan to change anything yet. I will keep you posted if I find the alternative method.

In the meantime I will just add an action for using clazy without this one warning. Then we see what we change or not

**Comment by gr5** [comment]
I opened the 4 .ui files in the design editor in qt creator and was able to move components around and such.  It all seems fine.  I did not save any changes to the ui files of course.

Then I built and ran it and used the 4 related windows. They are all fine.

So editing is still working fine.  Functionality is still working fine.  So I'm going to merge now.

**Comment by gr5** [comment]
By the way, the only build errors left seem to be in armadillo so new warnings will *really* stand out now.  I understand that these are also fixed in a newer version of armadillo but there's really not very many left.

**Comment by atsju** [comment]
I just see now that I missed these 2
image

Also about the left warnings:
- armadillo has already been fixed, no more warning from there
- those about use-alpha are only on windows and it's a know compiler bug because it's a (very) old compiler version
- 2 are left in qwt

**Pull request merged**
