### PR TITLE
update SingleApplication, move sources and icons around, deletes unused icons and files

### PR DESCRIPTION
**Pull request by atsju**
- I started working on #82 so it will fix userColorMapDlg closing on app closing.
- I had this one time memory leak from SingleApplication and I noticed this was [well maintained and this had been fixed](https://github.com/itay-grudev/SingleApplication/blob/master/CHANGELOG.md) so I updated to latest release.
- I separated external sources (bezier and singleApplication) to their own folder with their associated licence file.
Sources display well in QTcreator
image
- I deleted unused icons (their are in git history if we need one back some day)
- I moved all icons from base folder to /res folder
- Installer does not distribute icons anymore (only the ones used in HTML help files)
- removed mikeSpecsInterface from build (but kept file)
- deleted spline.h (confirmed by Dale)

### CODE REVIEW

**Comment by atsju** [comment]
I got back to one line per source in the .pro
Much easier to review and less merge conflicts

**Review by gr5 — APPROVED** [review]

**Comment by gr5** [comment]
When you move or rename a file, usually git figures it out as the old and new file are identical.  But if you also make an edit or maybe for reasons I don't understand, sometimes git marks the old file as deleted and the new file as created.

So in the future, please use git mv  (https://git-scm.com/docs/git-mv)

This way git knows you didn't intend to just delete and create but that you are renaming or moving a file.  This will help us follow edit history in git better (git will be smarter about it and show you historical edits made when the file had the old name or location), and also make reviews simpler.

I mean all the edits are still there but harder to find because the file that was edited was "deleted" (sometimes, if you don't use git mv).

**Comment by gr5** [comment]
> * I started working on [many dialogs don't close when application closes #82](https://github.com/githubdoe/DFTFringe/issues/82) so it will fix userColorMapDlg closing on app closing.

Wow you got distracted?  You only fixed one of them?  lol.  Okay.

**Comment by atsju** [comment]
> So in the future, please use git mv (https://git-scm.com/docs/git-mv)
I suppose you are talking about single_application. I had a look commit by commit and it has been modified in one and moved in an other. `git mv` would have changed nothing I think.

> Wow you got distracted? You only fixed one of them? lol. Okay.
Yes

**Comment by gr5** [comment]
> I suppose you are talking about single_application. I had a look commit by commit and it has been modified in one and moved in an other. `git mv` would have changed nothing I think.

Yes.  Well I guess it's just a github thing then.  Yeah I see it now in my git tools that it considered it a rename in one commit.  But I guess github didn't know how to show it as a rename *and* an edit.

**Pull request merged**
