### PR TITLE
corrected for edge mask not updating artificial null on initial o…

### PR DESCRIPTION
**Pull request by githubdoe**
Corrected edge mask not updating artificial null when config is constructed.  
Added code to save regions when a region is deleted.

### CODE REVIEW

**Comment by atsju** [comment]
The installer will appear [here ](https://github.com/githubdoe/DFTFringe/actions/runs/5446449190) as soon as Windows build is finished. 
It should run identically to locally but we never know.

**Comment by githubdoe** [comment]
What needs to happen next for this pull request to be completed.   Sorry I have forgotten what to do at this point.  I see it needs a Review.

**Comment by atsju** [comment]
someone needs to review it, approve it (or not and make some remarks for you to change before approval) and then one of you can merge it. Done.

Technically you can approve it yourself and merge it. But it's supposed to be peer review.

@gr5 can you review this PR of @githubdoe ?

**Comment by githubdoe** [comment]
Anyone want to take on that task?

**Comment by gr5** [comment]
I'll look at it now.

**Comment by gr5** [comment]
Code looks fine.  I tested the code and the specified bug is fixed.  However...

load/save doesn't work great (unless it's a feature)

If I select an edge mask, save it using the save button on the mirror config, change the edge mask checkbox and reload the mirror config file (.ini file) that I just saved, the edge mask is not updated in any way.  Maybe this is okay?  Maybe edge mask isn't technically part of the mirror config?

I know this is a different bug so Dale let me know if you will fix that now or not and if not I'll approve this PR (or you can approve it yourself, lol).

**Comment by githubdoe** [comment]
Thanks,  I think I should fix it now.

**Comment by gr5** [comment]
@githubdoe 
So .ini behavior hasn't changed.  Is the edge mask supposed to be saved in the ini file or not?  I'm guessing not.  Just want to confirm.  Will look at OLN behavior next.

**Comment by gr5** [comment]
OLN functionality works fine.  yes/no decision is confusing but accurate so I guess it's fine.

mirror config calls it "edge mask".  your new popup message calls it "outline mask".  Let's please stick with "edge mask".  Therefore in popup please change "outline mask" to "edge mask"
and please fix spelling of "differnt" to "different" (also in popup message)

**Comment by githubdoe** [comment]
Probably should be saved in the mirror config.ini.  But I never did and probably won't at this time.  Is saved in the QSettings so it is persistent.

**Comment by gr5** [comment]
That's fine.  Can you just fix the wording in the popup message?  Then I'll approve and pull this.

**Review by gr5 — APPROVED** [review]

**Pull request merged**
