### PR TITLE
Code changes required for the macOS version.

### PR DESCRIPTION
**Pull request by Interferometry**
- reworked main project file
- a minor code changes

### CODE REVIEW

**Comment by Interferometry** [comment]
I'll have a look at what I broke later on... probably the project file.

**Comment by atsju** [comment]
Excellent ! Thanks for the PR.
Yes it's probably the project file that is brocken for windows. 

For everybody's info, I will not be available until next Tuesday for test and reviews.

**Comment by Interferometry** [comment]
Okay this is fixed now.

**Comment by gr5** [comment]
all checks have passed and you mostly edited the pro file that Dale and I don't use so this should be easy.  Still, I'll look it over tomorrow.

**Comment by Interferometry** [comment]
Thanks for approving the PR, @gr5.

@atsju I've got some of it done already. The tricky part is the entitlements and signing once the application is assembled. Its been while since I last did some of this.

I've got a private repo setup to try things out for the CI. So far, so good, but thank you - I'll ask for help if I get stuck!

**Pull request merged**
