### PR TITLE
artifact with installer for windows

### LINKED ISSUE #26: Missing files in github
I realize there are several dozen files missing in this repository.  I'll add them.  None are crucial.  Some are jpg files needed for the help documentation (html files) and some are color maps.  Nothing critical.  I'll take care of this.  This issue is to remind me to rectify this.

### PR DESCRIPTION
**Pull request by atsju**
In this PR I will use QT installer framework to make installers. I use this instead of historial NSIS because it is multi-platform.
good link to learn : https://www.youtube.com/watch?v=1pKMcwJZay4

### Before merge I need:
- [x] installer for windows
- [x] use windeployqt to list and copy dependencies instead manual work
- [x] fix #26 

### do this separate to keep small steps
- [ ] installer for linux
- [ ] check which licences would need to be prompted (I suppose none is required for end user. Double check is required) or added in installation folder

### This can be done in a separate PR as artifacts already benefit from installer even without release:
- [ ] action to make release in one click (no local build)
- [ ] automated version and date update in releases

### Mac is not supported today. Keep this for later
- [ ] missing build and installer for mac

### CODE REVIEW

**Comment by atsju** [comment]
@gr5 kindly try out the new installer artifact https://github.com/githubdoe/DFTFringe/actions/runs/5382280050?pr=32 to confirm if needed files are present.

Any feedback is welcome

**Comment by gr5** [comment]
Is there a way to get rid of the "select the components you want to install" part of it?

Also it doesn't create a "start menu" shortcut and it doesn't create a desktop icon.  Either of those (not necessarily both) would be nice.

Otherwise people might not be able to find it after installation. We should at least warn them: "this does not create any desktop shortcuts or anything so pay attention where this is going to be installed".

**Comment by gr5** [comment]
Other than that it worked quite well.  It installed all the files I would expect it to install and is functioning.  I tested an igram and it worked fine.

**Comment by atsju** [comment]
> Is there a way to get rid of the "select the components you want to install" part of it?
> 
> Also it doesn't create a "start menu" shortcut and it doesn't create a desktop icon. Either of those (not necessarily both) would be nice.
> 
> Otherwise people might not be able to find it after installation. We should at least warn them: "this does not create any desktop shortcuts or anything so pay attention where this is going to be installed".

I suppose it's possible. I will have a look on how to do this.

**Comment by atsju** [comment]
New installer will be available here https://github.com/githubdoe/DFTFringe/actions/runs/5398944554?pr=32
I'm quite happy with the outcome (several shortcuts in start menu).  Please review. 

I think I introduced some whitespace changes in HTML help files. You can ease review using:
image

Other changes will be done in different PRs as there is already quite a lot here.

Note that merging will close #26. If we decide that we want to change default colormap, a new issue should probably be opened.

**Comment by gr5** [comment]
Bad news:  It still asks about which components to install, it *does* ask about where to put shortcuts in the start menu which is nice but it doesn't actually do anything.

Good news: It's just one file now (previous installer you unzipped to about 4 files and a subfolder and then had to guess which one to run - now it's just one installer)

**Comment by atsju** [comment]
> Could you please look into it and see if you can fix this? I think the issue is that usually you check out and then in with git but possibly these html files came from the installer? Can you do a force checkout or something? Or play with the CRLF settings?

Yes CRLF are whitespaces. I'm used to it and can sure fix it as you require. 

> Bad news: It still asks about which components to install, it does ask about where to put shortcuts in the start menu which is nice but it doesn't actually do anything.

Strange. On my Win10 I get Welcome, install folder, start menu folder, install => no component question
Also the start menu folder choice is working for me
image

Previous installer you tried in this PR should already have only one executable. Please double check you unzip to an empty folder ? Are using the correct installer ? deleted previous install before execution ? If it's the case, then please send me captures by email so that I figure something out. Note I have no previous experience, I'm learning to use the tool.

**Comment by gr5** [comment]
I have "windows 10 home".  Not only isn't in the "d"s, if I search for "DFTF" and I had installed it in c:\dftf then it is not found but if I install in c:\users\gr  then it is found.  Neither location installs it in the start menu.
start_menu

**Comment by atsju** [comment]
@gr5  could you run latest installer from commandline ? `DFTFringeInstaller.exe -ddd` d is for verbose. Let's see if this learns us something.
link to installer https://github.com/githubdoe/DFTFringe/actions/runs/5402481936

**Comment by gr5** [comment]
Now it is working!??  I ran from command line with -ddd and it worked so I ran the installer from explorer and put it into a different location with a different setup folder and that worked also.  I will test on my laptop later today or tomorrow but I think it's good now.

Also this is the first version that didn't ask me about components to install.  So I think you are done.

I guess a small improvement would be if the folder that these 2 shortcuts go into also used the dftfringe icon.  I don't know if that's easy or not.  But really it doesn't matter much as it seems to find the "app" directly as well if you search just for "dftf" after hitting the windows key.

**Comment by atsju** [comment]
> Now it is working!?? I ran from command line with -ddd and it worked so I ran the installer from explorer and put it into a different location with a different setup folder and that worked also. I will test on my laptop later today or tomorrow but I think it's good now.
> 
> Also this is the first version that didn't ask me about components to install. So I think you are done.

My best guess is you mixed up the installers and installed an older .exe before... Because I changed nothing.

> I guess a small improvement would be if the folder that these 2 shortcuts go into also used the dftfringe icon. I don't know if that's easy or not. But really it doesn't matter much as it seems to find the "app" directly as well if you search just for "dftf" after hitting the windows key.

I don't hink this is possible. I have no other application that would make me think it's possible to change picture of a folder.

**Comment by gr5** [comment]
Maybe it wasn't fully built?  Anyway it's good now.

**Comment by atsju** [comment]
> Maybe it wasn't fully built? Anyway it's good now.

artifact is uploaded once build is finished. And I also personally tested the artifacts you tried :(

**Comment by gr5** [comment]
I must have run the older one then but here is the sequence from my memory:
ver 1) asked about components, didn't ask about start menu, zip file had multiple components inside (or did I install something else this morning with multiple components and forgot already??)
ver 2) only had a single exe inside the zip file which was an all-in-one installer, asked about components, asked about start menu folder name but didn't create anything
ver 3) did *not* ask about components, asked about start menu folder and *did* install properly into start menu

But I don't think we should worry about it.  It's working now.

**Comment by gr5** [comment]
:(

Didn't work on my laptop which has win11.  It installed where I asked it to install (DFTA folder) but didn't create start menu shortcuts.  However start menu is pretty damn smart and if I type dftf it seems to find the raw exe file and launchs I think but it's finding an older install in a different folder.  But I think if this was the only version on the pc then it would show the latest install.  Hopefully.  Anyway here is the output:

Installer Framework SHA1: 9633659744b7bb734f67cabd720e5fa5e3af0a78
[0] Arguments: DFTFringeInstaller.exe, -ddd
[0] Resource tree:
[0]      :/translations
[0]      :/translations/ifw_zh_CN.qm
[0]      :/translations/ifw_pt_BR.qm
[0]      :/translations/qt_ar.qm
[1]      :/translations/qt_ca.qm
[1]      :/translations/qt_da.qm
[1]      :/translations/qt_de.qm
[1]      :/translations/qt_en.qm
[1]      :/translations/qt_es.qm
[1]      :/translations/qt_fr.qm
[1]      :/translations/qt_hu.qm
[1]      :/translations/qt_ja.qm
[1]      :/translations/qt_it.qm
[1]      :/translations/qt_ko.qm
[1]      :/translations/qt_pl.qm
[1]      :/translations/qt_pt.qm
[1]      :/translations/qt_ru.qm
[1]      :/translations/ifw_ar.qm
[2]      :/translations/ifw_ca.qm
[2]      :/translations/ifw_de.qm
[2]      :/translations/ifw_da.qm
[2]      :/translations/ifw_es.qm
[2]      :/translations/ifw_en.qm
[3]      :/translations/ifw_fr.qm
[3]      :/translations/ifw_hu.qm
[3]      :/translations/ifw_it.qm
[3]      :/translations/ifw_ja.qm
[3]      :/translations/ifw_ko.qm
[3]      :/translations/ifw_pl.qm
[4]      :/translations/ifw_pt.qm
[4]      :/translations/ifw_ru.qm
[4]      :/translations/qt_zh_CN.qm
[4]      :/uninstall.png
[4]      :/installer.png
[5]      :/installer.ico
[5]      :/keepinstalled.png
[5]      :/installer.icns
[5]      :/install.png
[5]      :/keepuninstalled.png
[6]      :/qgradient
[6]      :/qgradient/webgradients.binaryjson
[20] Operations sanity check succeeded.
[23] Using metadata cache from "C:/Users/gr/AppData/Local/cache\\qt-installer-framework\\dd1d903d-ac56-37e2-8e9d-c919380a91d4"
[23] Found 0 cached items.
[23] Language: en-US
[3519] Fetching latest update information...
[3528] Url is: "://metadata/"
[3529] Loading component scripts...
[18193] Selected components without dependencies:
com.githubdoe.DFTFringe
[18214] Installation space required: "166.79 MB" Temporary space required: "0.00 bytes" Local repository size: "0.00 bytes"
[39278] Cache and install directories are on the same volume. Volume mount point: "C:\\" Free space available: "630.32 GB"
[39849] cancelInstallation : DFTFringe Installer Question : Do you want to quit the installer application? Yes|No
[44012] backup  operation: Mkdir
[44012]         - arguments: C:/Users/gr/DFTA
[44013] Done
[44014] perform  operation: Mkdir
[44014]         - arguments: C:/Users/gr/DFTA
[44015] Done
[44015] Preparing the installation...
[44016] Install size: 1 components
[44025] Preparing to unpack components...
[44026] backup com.githubdoe.DFTFringe concurrent operation: Extract
[44027]         - arguments: installer://com.githubdoe.DFTFringe/a.b.cColorMaps.7z, C:/Users/gr/DFTA
[44027] Started
[44029] backup com.githubdoe.DFTFringe concurrent operation: Extract
[44029]         - arguments: installer://com.githubdoe.DFTFringe/a.b.cimageformats.7z, C:/Users/gr/DFTA
[44030] Started
[44030] backup com.githubdoe.DFTFringe concurrent operation: Extract
[44030]         - arguments: installer://com.githubdoe.DFTFringe/a.b.cplatforms.7z, C:/Users/gr/DFTA
[44031] Started
[44031] backup com.githubdoe.DFTFringe concurrent operation: Extract
[44031]         - arguments: installer://com.githubdoe.DFTFringe/a.b.cres.7z, C:/Users/gr/DFTA
[44032] Started
[44032] backup com.githubdoe.DFTFringe concurrent operation: Extract
[44032]         - arguments: installer://com.githubdoe.DFTFringe/a.b.ctranslations.7z, C:/Users/gr/DFTA
[44033] Started
[44033] backup com.githubdoe.DFTFringe concurrent operation: Extract
[44033]         - arguments: installer://com.githubdoe.DFTFringe/a.b.ccontent.7z, C:/Users/gr/DFTA
[44033] Started
[44038] Unpacking components...
[44038] perform com.githubdoe.DFTFringe concurrent operation: Extract
[44038]         - arguments: installer://com.githubdoe.DFTFringe/a.b.ccontent.7z, C:/Users/gr/DFTA
[44039] Started
[44039] perform com.githubdoe.DFTFringe concurrent operation: Extract
[44039]         - arguments: installer://com.githubdoe.DFTFringe/a.b.cres.7z, C:/Users/gr/DFTA
[44039] Started
[44040] perform com.githubdoe.DFTFringe concurrent operation: Extract
[44040]         - arguments: installer://com.githubdoe.DFTFringe/a.b.cplatforms.7z, C:/Users/gr/DFTA
[44040] Started
[44040] perform com.githubdoe.DFTFringe concurrent operation: Extract
[44040]         - arguments: installer://com.githubdoe.DFTFringe/a.b.cimageformats.7z, C:/Users/gr/DFTA
[44041] Started
[44042] perform com.githubdoe.DFTFringe concurrent operation: Extract
[44042]         - arguments: installer://com.githubdoe.DFTFringe/a.b.cColorMaps.7z, C:/Users/gr/DFTA
[44042] Started
[44046] perform com.githubdoe.DFTFringe concurrent operation: Extract
[44049]         - arguments: installer://com.githubdoe.DFTFringe/a.b.ctranslations.7z, C:/Users/gr/DFTA
[44052] Started
[45349] Installing component DFTFringe
[45351] backup com.githubdoe.DFTFringe operation: CreateShortcut
[45351]         - arguments: C:/Users/gr/DFTA/DFTFringe.exe, C:\Users\gr\AppData\Roaming\Microsoft\Windows\Start Menu\Programs\DFTFA/DFTFringe.lnk
[45352] Done
[45352] perform com.githubdoe.DFTFringe operation: CreateShortcut
[45355]         - arguments: C:/Users/gr/DFTA/DFTFringe.exe, C:\Users\gr\AppData\Roaming\Microsoft\Windows\Start Menu\Programs\DFTFA/DFTFringe.lnk
[45409] Done
[45410] backup com.githubdoe.DFTFringe operation: CreateShortcut
[45413]         - arguments: C:/Users/gr/DFTA/res/Help/help.html, C:\Users\gr\AppData\Roaming\Microsoft\Windows\Start Menu\Programs\DFTFA/DFTFringe help.lnk
[45416] Done
[45417] perform com.githubdoe.DFTFringe operation: CreateShortcut
[45419]         - arguments: C:/Users/gr/DFTA/res/Help/help.html, C:\Users\gr\AppData\Roaming\Microsoft\Windows\Start Menu\Programs\DFTFA/DFTFringe help.lnk
[45429] Done
[45430] backup com.githubdoe.DFTFringe operation: CreateShortcut
[45432]         - arguments: C:/Users/gr/DFTA/maintenancetool.exe, C:\Users\gr\AppData\Roaming\Microsoft\Windows\Start Menu\Programs\DFTFA/uninstall.lnk
[45436] Done
[45436] perform com.githubdoe.DFTFringe operation: CreateShortcut
[45439]         - arguments: C:/Users/gr/DFTA/maintenancetool.exe, C:\Users\gr\AppData\Roaming\Microsoft\Windows\Start Menu\Programs\DFTFA/uninstall.lnk
[45445] Done
[45450] Writing maintenance tool: "C:/Users/gr/DFTA/maintenancetool.exe.new"
[45453] Writing maintenance tool.
[45484] Wrote permissions for maintenance tool.
[45523] Maintenance tool hard restart: false.
[45527] Installation finished!
[- 100%]
C:\Users\gr\Desktop>

Okay so it does properly create the above lnk files in the indicated folders.  And there are lots of other folders for other applications there.  But it seems win11 ignores all that.  win11 is very different.  It doesn't have the start menu stuff.  But it does seem able to find all exe files that were installed recently so maybe it doesn't matter.  I guess I need to uninstall all other copies of dftfringe to make sure it can find the one just installed.

I need to pack up and leave so I'll look at this some more tonight or tomorrow.

**Comment by gr5** [comment]
One more comment - having a desktop icon would be nice.  :)  Then maybe start menu doesn't matter.  I think the old dftfringe installer did that? maybe?

**Comment by atsju** [comment]
>Okay so it does properly create the above lnk files in the indicated folders. And there are lots of other folders for other applications there. But it seems win11 ignores all that. win11 is very different. It doesn't have the start menu stuff. But it does seem able to find all exe files that were installed recently so maybe it doesn't matter. I guess I need to uninstall all other copies of dftfringe to make sure it can find the one just installed.

Windows 11 seems to be quite different from windows 10. unfortunatelly i don't hava  machine to try out. Thanks for the verbose output. Can you confirm it's not under "all apps" ?
image


>I need to pack up and leave so I'll look at this some more tonight or tomorrow.

We are not in a hurry. Enjoy your life :)

>One more comment - having a desktop icon would be nice. :) Then maybe start menu doesn't matter. I think the old dftfringe installer did that? maybe?

6.2 did not do it. But this is definitely something QT installer framework should be able to do. Personally I think desktop shortcuts are not used soo much anymore. But I can have a look on how to add it.

**Comment by gr5** [comment]
> Can you confirm it's not under "all apps" ?

Ah!  There it is.  Yep.  I never noticed that before.  I think we are all set for windows installer.  Except _possibly_ the desktop icon thing.

**Comment by atsju** [comment]
This one was not easy but you now have a checkbox to check to add the desktop shortcut
https://github.com/githubdoe/DFTFringe/actions/runs/5413859501

**Comment by gr5** [comment]
Works great!

**Comment by gr5** [comment]
So I tried the uninstaller and it works fine - I went to windows "add or remove programs" and searched for DFTF and found it.  However the version that you have in the installer shows up.  I had noticed you had "a.b.c" for the installer version but I couldn't see anyplace it was visible so I forgot about that until I did the uninstaller.  It's not a big deal but ideally the a.b.c in the xml files should batch the latest version tag.

Screenshot 2023-06-30 072332

**Comment by atsju** [comment]
> So I tried the uninstaller and it works fine - I went to windows "add or remove programs" and searched for DFTF and found it. However the version that you have in the installer shows up. I had noticed you had "a.b.c" for the installer version but I couldn't see anyplace it was visible so I forgot about that until I did the uninstaller. It's not a big deal but ideally the a.b.c in the xml files should batch the latest version tag.

Yes you are correct. I put a.b.c to be obvioulsy wrong. 

I plan to do this as next step in a separate PR (I don't know when) to have automated releases in one click with correct versions info. I don't want to have to change version infos at several places manually as it will ultimately fail because humans.

**Comment by gr5** [comment]
Okay I think this is ready for me to approve.  Do you have any more planned changes?

By the way the "add remove" uninstall works great.  Also there were other easy ways to uninstall - I think I right clicked on something - the icon or the exe or something and windows was like do you want to uninstall?  So this is looking great right now.

Any more changes or can I do the approval now?

**Comment by atsju** [comment]
> Any more changes or can I do the approval now?

I'm working on next PR for automated releases. Still a learning curve. Nothing more planned here, kindly merge whenever ready

**Review by gr5 — APPROVED** [review]
Looks great.

**Pull request merged**
